### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by catavallejos** [saintland/RAEN#1]
Hi @saintland,

Sadly, this package has been recently [removed from CRAN](https://cran.r-project.org/web/packages/RAEN/index.html) due to its dependency to `fastcmprsk`. Do you have any plans to fix this?

Best,

Catalina

**Comment by saintland** [comment]
HI Catalina:
One quick solution is to install fastcmprsk and RAEN via github.
install.packages("devtools")
devtools::install_github(“erickawaguchi/fastcmprsk”)
install_github('saintland/RAEN')

In the long run, I am trying to rewrite the fastcmprsk codes and integrate them into RAEN.

Thanks,

Han Sun

**Comment by catavallejos** [comment]
Thank you so much for your response. It's great to hear that you have plans to reinstate the package in CRAN.
